#!/usr/bin/env ruby

require 'fileutils'
require 'yaml'

include FileUtils

def copy_backup base, target, last_target
  if File.exists?(last_target)
    rm_r last_target
  end
  if File.exists?(target)
    mv target, last_target
  end
  system "cp", "-al", base, target
end

require 'optparse'

verbose = false
dry_run = false

OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options]"

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    verbose = v
  end
  opts.on("-n", "--[no-]dry-run", "Dont process") do |v|
    dry_run = v
  end
end.parse!

if ARGV.size != 1
  raise "usage: #$0 [-v] [-n] <root>"
end

root = ARGV.first
config_file = File.join(root, "config.yml")
config = YAML.load(File.read(config_file))

remote = config["remote"]
id_file = config["key"]
paths = config["paths"]

if paths.nil?
  paths = { "root" => "/" }
end

now = Time.now
name = "current"

paths.each do |path_name, path|
  dest = File.join(root, path_name)
  mkpath dest
  backup_dir = File.join(dest, name)

  cmd = [
    "rsync",
    "--archive",
    "--one-file-system",
    "--delete-delay",
    "--compress",
    "--rsh", "ssh -i #{id_file}",
  ]
  cmd << "--verbose" if verbose
  cmd << "--dry-run" if dry_run
  cmd += [
    remote + ":" + path,
    backup_dir,
  ]

  puts cmd.inspect if verbose
  break unless system *cmd

  target = File.join(dest, "month")
  last_target = File.join(dest, "month.last")
  if now.day == 1 or !File.exists?(target)
    copy_backup(backup_dir, target, last_target)
  end

  target = File.join(dest, "week")
  last_target = File.join(dest, "week.last")
  if now.wday == 0 or !File.exists?(target)
    copy_backup(backup_dir, target, last_target)
  end
end
