#!/usr/bin/env ruby

require 'fileutils'
require 'yaml'

include FileUtils

def copy_backup base, target, last_target
  if File.exists?(last_target)
    rm_r last_target
  end
  if File.exists?(target)
    mv target, last_target
  end
  system "cp", "-al", base, target
end

if ARGV.size != 1
  raise "usage: #$0 <root>"
end

root = ARGV.first 
config_file = File.join(root, "config.yml")
config = YAML.load(File.read(config_file))

remote = config["remote"]
id_file = config["key"]
paths = config["paths"]

if paths.nil?
  paths = { "root" => "/" }
end

known_hosts_file = File.expand_path("~/.ssh/known_hosts")
if File.exists? known_hosts_file
  known_hosts = File.read(known_hosts_file).split("\n")
else
  known_hosts = []
end

if known_hosts.grep(/^#{Regexp.escape remote} /).empty?
  host_key = %x(ssh-keyscan -t rsa,dsa #{remote} 2>/dev/null)
  puts "Adding host key #{host_key}"
  known_hosts << host_key
  File.open(known_hosts_file, "w") { |f| f.puts known_hosts.join("\n") }
end

now = Time.now
name = "current"

paths.each do |path_name, path|
  dest = File.join(root, path_name)
  mkpath dest
  backup_dir = File.join(dest, name)

  cmd = [
    "rsync",
    "--archive",
#    "--verbose",
    "--one-file-system",
    "--delete-delay",
    "--compress",
    "--rsh", "ssh -i #{id_file}",
  ]
  cmd += [
    remote + ":" + path,
    backup_dir,
  ]

#  puts cmd.inspect
  break unless system *cmd

  target = File.join(dest, "month")
  last_target = File.join(dest, "month.last")
  if now.day == 1 or !File.exists?(target)
    copy_backup(backup_dir, target, last_target)
  end

  target = File.join(dest, "week")
  last_target = File.join(dest, "week.last")
  if now.wday == 0 or !File.exists?(target)
    copy_backup(backup_dir, target, last_target)
  end
end
